# Generated by Django 3.1.5 on 2021-01-07 14:59

from django.db import migrations, models
import neon.models


class Migration(migrations.Migration):

    dependencies = [
        ('neon', '0002_auto_20210107_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(height_field='height', upload_to=neon.models.user_directory_path, width_field='width'),
        ),
    ]
